baseurl: "/resumecards" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://ellekasai.github.io" # the base hostname & protocol for your site
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
